<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>
<body>
  <input type="text">
<script>
  /*
    45.1 비동기 처리를 위한 콜백 패턴의 단점
  */
  
  {
    // GET 요청을 위한 비동기 함수
    const get = url => { // 비동기 함수. 함수 내부에 비동기로 동작하는 코드를 포함한 함수
      const xhr = new XMLHttpRequest()
      xhr.open('GET', url)
      xhr.send()

      xhr.onload = () => {
        if (xhr.status === 200) console.log(JSON.parse(xhr.response))
        else console.log(`${xhr.status} ${xhr.statusText}`)
      }
    }
    get('http://jsonplaceholder.typicode.com/posts/1')

    /*
      {
        title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit", body: "quia et suscipit↵suscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto"}
        body: "quia et suscipit↵suscipit recusandae consequuntur expedita et cum↵reprehenderit molestiae ut ut quas totam↵nostrum rerum est autem sunt rem eveniet architecto"
        id: 1
        title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"
        userId: 1
      }

      비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않는다 해도 기다리지 않고 즉시 종료된다. 
      
      즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 
      
      따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

      GET 요청을 전송하는 서버의 응답을 전달받는 get 함수도 비동기 함수다.

      get 함수가 비동기 함수인 이유는 get 함수 내부의 onload 이벤트 핸들러가 비동기 동작하기 때문이다.
    */
  }

  {
    let g = 0
    
    // 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다
    setTimeout(() => { g = 100 }, 0)
    console.log(g) // 0
  }

  {
    // GET 요청을 위한 비동기 함수
    const get = url => {
      const xhr = new XMLHttpRequest()
      xhr.open('GET', url)
      xhr.send()

      xhr.onload = () => {
        if (xhr.status === 200) return JSON.parse(xhr.response)
        else console.log(`${xhr.status} ${xhr.statusText}`)
      }
    }
    const response = get('http://jsonplaceholder.typicode.com/posts/1')
    console.log('response : ', response) // undefined
  }

  {
    document.querySelector('input').oninput = function () {
      console.log(this.value)
      return this.value
    }
  }

  {
    let todos

    // GET 요청을 위한 비동기 함수
    const get = url => {
      const xhr = new XMLHttpRequest()
      xhr.open('GET', url)
      xhr.send()

      xhr.onload = () => {
        if (xhr.status === 200) todos = JSON.parse(xhr.response)
        else console.log(`${xhr.status} ${xhr.statusText}`)
      }
    }
    get('http://jsonplaceholder.typicode.com/posts/1')
    console.log('todos : ', todos) // undefined
  }

  /*
    xhr.onload 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니다. xhr.onload 이벤트 핸들러는 load 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

    이벤트 핸들러도 함수이므로 이벤트 핸들러의 평가 ->
    이벤트 핸들러의 실행 컨텍스트 생성 ->
    콜 스택에 푸시 ->
    이벤트 핸들러 실행 과정을 거친다.
  */

  /*
    이처럼 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 
    상위 스코프의 변수에 할당할 수도 없다. 
    
    따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 
    
    이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다.
    
    필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달할 수 있다.
  */

  {
    // GET 요청을 위한 비동기 함수
    const get = (url, successCallback, failureCallback) => {
      const xhr = new XMLHttpRequest()
      xhr.open('GET', url)
      xhr.send()

      xhr.onload = () => {
        if (xhr.status === 200) {
          // 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답ㅇ에 대한 후속 처리를 한다.

          // 콜백 헬.callback hell
          successCallback(JSON.parse(xhr.response))
        } else {
          // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
          console.log(`${xhr.status} ${xhr.statusText}`)
        }
      }
    }

    // id가 1인 post를 취득
    // 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달
    get('http://jsonplaceholder.typicode.com/posts/1', console.log, console.error)
  }

  /*
    45.1.2 에러 처리의 한계
  */

  {
    try {
      setTimeout(() => {
        // throw new Error('Error!')
      }, 1000)
    } catch (e) {
      // 에러를 캐치하지 못한다.
      console.log('캐치한 에러', e)
    }
  }

  /*
    try, catch, finally 문
    try 코드 블록에 포함된 문 중에서 에러가 발생하면 해당 에러는 catch 문의 err 변수에 전달되고 catch 코드 블록이 실행된다. finally 코드 블록은 에어 발생과 상관없이 반드시 한 번 실행된다. try, catch, finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다

    에러는 호출자caller 방향으로 전파되다. 즉, 콜 스택의 아래 방향으로 전파.
  */

  /*
    45.2 프로미스의 생성

    resolve, reject 함수 인자로 전달받는다.
  */

  {
    // 프로미스 생성
    const promise = new Promise((resolve, reject) => {
      // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행
      if ( true ) { /* 비동기 처리 성공 */
        resolve('result')
      } else { /* 비동기 처리 실패 */
        reject('failure reason')
      }
    })
  }

  {
    // GET 요청을 위한 비동기 함수. 함수 내부에서 프로미스를 생성하고 반환한다.
    const promiseGet = (url) => {
      return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest()
        xhr.open('GET', url)
        xhr.send()

        xhr.onload = () => {
          if (xhr.status === 200) {
            // 성공적으로 응답을 전달받으면 resolve 함수 호출
            resolve(JSON.parse(xhr.response))
          } else {
            // 에러 처리를 위해 reject 함수 호출
            reject(new Error(xhr.status))
          }
        }
      })
    }

    // promiseGet 함수는 프로미스를 반환
    promiseGet('http://jsonplaceholder.typicode.com/posts/1')
  }

  /*
    비동기 처리 진행되고 있는지 나타내는 상태.state
    -------------------------------------------------------------------------------
    pending     비동기 처리가 아직 수행되지 않는 상태   프로미스가 생성된 직후 기본 상태
    fulfilled   비동기 처리가 수행된 상태(성공)         resolve 함수 호출
    rejected    비동기 처리가 수행된 상태(실패)         reject 함수 호출
    -------------------------------------------------------------------------------

    resolve(value)
    reject(error)
  */

  {
   // fulfilled된 프로미스
   const fulfilled = new Promise(resolve => resolve(1))

   // rejected된 프로미스
   const rejected = new Promise((_, reject) => reject(new Error('Error occurred')))
  }

  /*
    45.3 프로미스의 후속 처리 메서드

    then, catch, finally

    프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출
  */
  {
    // fulfilled된 프로미스
    const fulfilled = new Promise(resolve => resolve(1))
    .then(v => console.log(v), e => console.error(e))

    // rejected된 프로미스
    const rejected = new Promise((_, reject) => reject(new Error('Error occurred')))
    .then(v => console.log(v), e => console.error(e))

    new Promise((_, reject) => reject(new Error('rejected')))
    .catch(e => console.log(e))
   
    new Promise(() => {})
    .finally(() => console.log('finally'))
  }

  {
    // GET 요청을 위한 비동기 함수. 함수 내부에서 프로미스를 생성하고 반환
    const promiseGet = (url) => {
      return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest()
        xhr.open('GET', url)
        xhr.send()

        xhr.onload = () => {
          if (xhr.status === 200) {
            // 성공적으로 응답을 전달받으면 resolve 함수 호출
            resolve(JSON.parse(xhr.response))
          } else {
            // 에러 처리를 위해 reject 함수 호출
            reject(new Error(xhr.status))
          }
        }
      })
    }

    // promiseGet 함수는 프로미스를 반환
    promiseGet('http://jsonplaceholder.typicode.com/posts/1')
      .then(res => console.log('res!! : ', res))
      .catch(err => console.log(err))
      .finally(() => console.log('Bye!'))
  }
</script>
</body>
</html>